### ISSUE TITLE
Provide a procedure that updates K8s-based NE from one version to another.

### ISSUE THREAD

**Issue by konstan** [nuvlaedge/deployment#112]

**Comment by giovannibianco** [comment]
Some thoughts... reading the update code. OK, it's docker oriented.
For the kubernetes-installed NE can we safely assume that helm is installed?
If so, then [https://pypi.org/project/pyhelm/] may be the way to go...
We can use the k8s connector as other actions then use helm to update as usual?

**Comment by giovannibianco** [comment]
- [] check the version

**Comment by giovannibianco** [comment]
A rather large note while found in testing...
A user wants to upgrade the NE and is presented with the update panel...
there is the current version, possible versions to update to and the peripherals (all not checked).
The user must know which peripherals were checked in the original deployment...
Why?
Because if they are all left unchecked when helm is run the payload does not contain these peripherals.
The behaviour of `helm upgrade` will be to upgrade to exactly as described.
So some peripherals may be removed unintentionally if the user assumes that the original set may be preserved.

**Comment by giovannibianco** [comment]
Looking through the API, I cannot find where the current state of the deployed NE is held... i.e what peripherals are activated and VPN client etc.
So I'm not sure where the initial deployments are stored and what happens subsequently when helm runs an upgrade and "overwrites" the peripherals deployment.

**Comment by giovannibianco** [comment]
Demoed on 2023/10/03
